
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show env
      run: env
    - name: Show context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Create Dockerfile in a new directory
      env:
        user: ${{secrets.user}}
        pw: ${{ secrets.pw }}
      run: |
        mkdir result
        cd result
        cat >Dockerfile <<EOF
        FROM node:12
        WORKDIR /vscode
        COPY . .
        EXPOSE 8081
        CMD bash
        EOF
        docker build -t phwhx/dummy:1.0 .
        docker login -u user -p pw
        docker push phwhx/dummy:1.0
